In [2]:
import numpy as np
a=np.array([1,34,5,8])
a

array([ 1, 34,  5,  8])

In [3]:
t=np.array((1,2,3,4))
t

array([1, 2, 3, 4])

In [4]:
a=np.arange(20,50,8)
a

array([20, 28, 36, 44])

In [6]:
a=np.random.randint(20,100,16).reshape(4,4)
a

array([[75, 46, 47, 96],
       [92, 90, 52, 61],
       [84, 43, 57, 41],
       [22, 34, 26, 95]])

### Pandas 
- it is one of the most important modules of data science
- used to work with data in the form of frames/table 
- stands for panel data
- data Analysis ,manipulation and cleaning
  - Data Analysis means analysising the data
    - Statistics of the data,volume of data etc
  - Data Manipulation means transforming the data from one format to another
    - Merging,Conmcatenmating etc
  - Data  cleaning means removing the data 
    - Null data means NaN (Not a number)
- 2 data structures in pandas
 - 1) Series
    - Sequential data
  - 2) DataFrame
    - Data in tabular format i.e., rows and columns
- **Instllation**
   - pip install pandas
   - import pandas

In [8]:
import pandas as pd
pd.__version__

'1.2.4'

In [9]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing'

In [10]:
# we can create series using str,tuple,list and dict
st="I am A.L.Sankeerthana"
pd.Series(st)

0    I am A.L.Sankeerthana
dtype: object

In [11]:
# try with input().split()
li=input("type your clg name: ").split()
pd.Series(li)

type your clg name: vr si


0    vr
1    si
dtype: object

In [12]:
print(pd.Series(li))

0    vr
1    si
dtype: object


In [13]:
li=input()
pd.Series(li)

1 2 3 4


0    1 2 3 4
dtype: object

In [15]:
l=int(input())
pd.Series(l)

1 2 3 4


ValueError: invalid literal for int() with base 10: '1 2 3 4'

In [16]:
#Using tuple/list
t=(6,7,3,4,5)
pd.Series(t)

0    6
1    7
2    3
3    4
4    5
dtype: int64

In [17]:
pd.Series(range(10,30,6))

0    10
1    16
2    22
3    28
dtype: int64

In [56]:
#using dictionary
dic={'34' : "thirty four",12:0,'tuple':(9,2,4),'list': [1,7,8]}
s=pd.Series(dic)
s

34       thirty four
12                 0
tuple      (9, 2, 4)
list       [1, 7, 8]
dtype: object

In [21]:
d={12,17,89}
pd.Series(d)

TypeError: 'set' type is unordered

In [23]:
import numpy as np
ar=np.arange(10,45,5)
a=pd.Series(ar)
a

0    10
1    15
2    20
3    25
4    30
5    35
6    40
dtype: int32

In [24]:
a[0]

10

In [25]:
a[0:4]

0    10
1    15
2    20
3    25
dtype: int32

In [27]:
a[0:len(a)]

0    10
1    15
2    20
3    25
4    30
5    35
6    40
dtype: int32

In [29]:
a.index

RangeIndex(start=0, stop=7, step=1)

In [33]:
a.index=[4,5,67,3,89,76,73]
a

4     10
5     15
67    20
3     25
89    30
76    35
73    40
dtype: int32

In [35]:
li2=[9,2,90,89,'hi']
ind=[n for n in range(3,8)]
pd.Series(li2,index=ind)

3     9
4     2
5    90
6    89
7    hi
dtype: object

In [37]:
# pass the user index to series created using dict
#len(dic)
ix=[num for num in range(10,14)]
pd.Series(dic,index=ix)

10    NaN
11    NaN
12      0
13    NaN
dtype: object

In [38]:
s.index

Index(['3', 12, 'tuple', 'list'], dtype='object')

In [39]:
s['tuple']

(9, 8)

In [40]:
s['tuple'][1]

8

In [41]:
a.index[4:76]

Int64Index([89, 76, 73], dtype='int64')

### DataFrames
- datab is in 2d format

In [57]:
import numpy as np
import pandas as pd
pd.DataFrame(dic)

34  12  tuple  list
0  thirty four   0      9     1
1  thirty four   0      2     7
2  thirty four   0      4     8

In [61]:
data={'int' : 90,'float': 90.73,'str':"keerthi",'roll': 67}
nk=pd.DataFrame(data,index=[5,6,89])
nk

int  float      str  roll
5    90  90.73  keerthi    67
6    90  90.73  keerthi    67
89   90  90.73  keerthi    67

In [62]:
pd.concat([s,nk])

0  float   int  roll      str
34     thirty four    NaN   NaN   NaN      NaN
12               0    NaN   NaN   NaN      NaN
tuple    (9, 2, 4)    NaN   NaN   NaN      NaN
list     [1, 7, 8]    NaN   NaN   NaN      NaN
5              NaN  90.73  90.0  67.0  keerthi
6              NaN  90.73  90.0  67.0  keerthi
89             NaN  90.73  90.0  67.0  keerthi

In [71]:
import pandas as pd
n={'name':"keer",'roll':67,'clg':"vrsec"}
a=pd.DataFrame(n,index=[100,99,98])
a
m={'int': 23,'float': 67.98,'str':'keer'}
b=pd.DataFrame(m,index=[23,34,45])
b
pd.concat([a,b])


name  roll    clg   int  float   str
100  keer  67.0  vrsec   NaN    NaN   NaN
99   keer  67.0  vrsec   NaN    NaN   NaN
98   keer  67.0  vrsec   NaN    NaN   NaN
23    NaN   NaN    NaN  23.0  67.98  keer
34    NaN   NaN    NaN  23.0  67.98  keer
45    NaN   NaN    NaN  23.0  67.98  keer